-- MySQL Script generated by MySQL Workbench
-- Sun Jul 21 00:31:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema buryto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buryto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buryto` DEFAULT CHARACTER SET utf8 ;
USE `buryto` ;

-- -----------------------------------------------------
-- Table `buryto`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buryto`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `price` INT NOT NULL,
  `imageurl` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buryto`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buryto`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `btc_address` VARCHAR(150) NULL,
  `eth_address` VARCHAR(150) NULL,
  `ltc_address` VARCHAR(150) NULL,
  `sol_address` VARCHAR(150) NULL,
  `profile_picture_url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `eth_address_UNIQUE` (`eth_address` ASC) VISIBLE,
  UNIQUE INDEX `btc_address_UNIQUE` (`btc_address` ASC) VISIBLE,
  UNIQUE INDEX `ltc_address_UNIQUE` (`ltc_address` ASC) VISIBLE,
  UNIQUE INDEX `sol_address_UNIQUE` (`sol_address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buryto`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buryto`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buryto`.`sales_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buryto`.`sales_has_users` (
  `sales_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`sales_id`, `users_id`),
  INDEX `fk_sales_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_sales_has_users_sales_idx` (`sales_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_has_users_sales`
    FOREIGN KEY (`sales_id`)
    REFERENCES `buryto`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `buryto`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buryto`.`users_has_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buryto`.`users_has_sales` (
  `user_id` INT NOT NULL,
  `sale_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `sale_id`),
  INDEX `fk_users_has_sales_sales1_idx` (`sale_id` ASC) VISIBLE,
  INDEX `fk_users_has_sales_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_sales_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `buryto`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_sales_sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `buryto`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buryto`.`users_has_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buryto`.`users_has_messages` (
  `sender_id` INT NOT NULL,
  `reciever_id` INT NOT NULL,
  PRIMARY KEY (`sender_id`, `reciever_id`),
  INDEX `fk_users_has_messages_messages1_idx` (`reciever_id` ASC) VISIBLE,
  INDEX `fk_users_has_messages_users1_idx` (`sender_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_messages_users1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `buryto`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_messages_messages1`
    FOREIGN KEY (`reciever_id`)
    REFERENCES `buryto`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
